#!/usr/bin/env bash
# Script to securely copy file to a remote host
if  [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp  -o StrictHostKeyChecking=no -i {$1} ${2}@${3}:~/ -i ${4}
