#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

#bHello World!
echo 'Hello World!' | sudo tee /var/www/html/index.html

# 301
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://hackerone.com/hack3dby0mar;\n\t}' /etc/nginx/sites-available/default

# 404 
echo "Hey, you! You lost?" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart