#!/usr/bin/env bash
# Install my load balancer

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 348624-web-01 54.160.117.191:80 check
    server 348624-web-02 18.210.17.222:80 check
"
apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
sudo echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart

