#!/usr/bin/env bash
# setup a load balancer

sudo apt update -y
sudo apt-get install haproxy=2.0.\* -y
sudo echo -e "frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 348624-web-01 3.90.80.8:80 check\n\tserver 348624-web-02 100.25.3.153:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart